apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordscapes-solver-api-ingress
  namespace: { { namespace } }
spec:
  tls:
    - secretName: wordscapes-solver-api-tls
      hosts:
        - { { hostname } }
  rules:
    - host: { { hostname } }
      http:
        paths:
          - backend:
              service:
                name: wordscapes-solver-api-service
                port:
                  name: springboot-port
            pathType: ImplementationSpecific