apiVersion: v1
kind: Service
metadata:
  name: wordscapes-solver-api-service
  namespace: { { namespace } }
spec:
  selector:
    app: wordscapes-solver-api
    branch: { { git_branch } }
  ports:
    - port: 8080
      name: springboot-port