name: build-pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: |
            ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Execute test suite
        run: ./mvnw test

  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    needs:
      - compile-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: |
            ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: javalin-seed-publish
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Build and publish Docker image
        run: ansible-playbook playbooks/build-and-publish-docker-image.yml

  deploy-to-k8s:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs:
      - publish-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: javalin-seed-deploy
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Deploy to K8s server
        run: ansible-playbook -vvv playbooks/k8s-deploy.yml

  send-notification:
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - compile-and-test
      - publish-docker-image
      - deploy-to-k8s

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1
